dist: trusty
sudo: required
language: node_js
node_js:
  - '16'

os:
  - linux

jobs:
  include:
    - stage: lint
      script:
        - ng lint
    - stage: test
      script:
        - npm run test:coverage
        - npm run report-coverage
    - stage: build & publish lib
      script:
        - npm run build:lib
        - npm run publish:lib
      if: branch = master
